[project]
name = "cuPosit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "icecream>=2.1.8",
    "ninja>=1.13.0",
    "numpy>=2.4.0",
    "torch>=2.9.1",
]
